#!/bin/bash
source /kb/deployment/user-env.sh
echo /kb/deployment/bin/awe-client -conf /kb/deployment/services/awe_service/conf/awec.cfg
/kb/deployment/bin/awe-client -conf /kb/deployment/services/awe_service/conf/awec.cfg
